
# ===================================================================
# Propiedades especificas de la aplicacion (microservicio)
# ===================================================================
info:
  arquetipo:
    version: #nmp.arquetipo.version#
  microservicio:
    nombre: #name#
    version: #version#
    descripcion: #description#
  spring-boot:
    version: #parent.version#

microservicio:
  cache: # Hibernate 2nd level cache, used by CacheConfiguration
    timeToLiveSeconds: 3600

cxf:
  path: /soap-api

tipocambio:
  convertidor:
    wsdlLocation: http://localhost:8083/soap-api/ConvertidorTipoCambio?wsdl

# mostrar o no mensajes soap entrantes y salientes
soap:
  mensaje:
    mostrar: false

thread:
    pool:
        size:
            core: 10
            max: 50
            queue: 1000
