# ===================================================================
# Configuración Spring Boot
#
# Configuración para el profile de Spring "local".
# Aquí puedes establecer la configuración necesaria para el perfil de
# desarrollo local con base de datos MySQL.
# ===================================================================

# ===================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
    port: 8084
management:
    shell:
        ssh:
            port: 2084

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/sivad-tablas-referencia?useUnicode=true&characterEncoding=utf8&useSSL=false
        name: sivad-tablas-referencia
        username: root
        password: password
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

# ===================================================================
# Propiedades especificas de la aplicacion (microservicio)
# ===================================================================
