# ===================================================================
# Configuración Spring Boot
#
# Configuración para el profile de Spring "dev".
# Aquí puedes establecer la configuración necesaria para el perfil de
# desarrollo.
# ===================================================================

# ===================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
    port: 8084
management:
    shell:
        ssh:
            port: 2084

spring:
    datasource:
        initialize: true
        schema: classpath:/schema-h2.sql
        data: classpath:/data-h2.sql
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/sivad_tablas_referencia;DB_CLOSE_DELAY=-1
        name:
        username: sivad
        password:
    h2:
        console:
            enabled: true
    jpa:
        database-platform: mx.com.nmp.ms.arquetipo.db.h2.FixedH2Dialect
        database: H2
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

tipocambio:
  convertidor:
    wsdlLocation: http://localhost:8083/soap-api/ConvertidorTipoCambio?wsdl
  consulta:
    wsdlLocation: http://localhost:8083/soap-api/ConsultaTipoCambio?wsdl

# ===================================================================
# Propiedades especificas de la aplicacion (microservicio)
# ===================================================================
application:
    # por defecto cors esta desactivado, descomentar las siguientes lineas para activarlo
    cors:
      allowed-origins: "*"
      allowed-methods: GET, PUT, POST, DELETE, OPTIONS
      allowed-headers: "*"
      exposed-headers:
      allow-credentials: true
      max-age: 1800
