DROP TABLE IF EXISTS JOURNAL_EVENT;
CREATE TABLE JOURNAL_EVENT
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    PRINCIPAL VARCHAR(50) NOT NULL,
    DATE TIMESTAMP,
    TYPE VARCHAR(255),
    PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS JOURNAL_ENTITY_EVENT;
CREATE TABLE JOURNAL_ENTITY_EVENT
(
    ID BIGINT NOT NULL,
    CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_ENTITY_EVENT ADD FOREIGN KEY (ID) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS JOURNAL_CUSTOM_EVENT;
CREATE TABLE JOURNAL_CUSTOM_EVENT
(
    ID BIGINT NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_CUSTOM_EVENT ADD FOREIGN KEY (ID) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS JOURNAL_EVENT_DATA;
CREATE TABLE JOURNAL_EVENT_DATA
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    EVENT BIGINT NOT NULL,
    PROPERTY VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_EVENT_DATA ADD FOREIGN KEY (EVENT) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS CFG_DIAMANTE_FACTOR;
CREATE TABLE CFG_DIAMANTE_FACTOR
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    FACTOR_MAXIMO DECIMAL(10, 3) NOT NULL,
    FACTOR_MEDIO DECIMAL(10, 3) NOT NULL,
    FACTOR_MINIMO DECIMAL(10, 3) NOT NULL,
    FECHA_CARGA TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);
ALTER TABLE CFG_DIAMANTE_FACTOR ADD CONSTRAINT PK_CFG_DIAMANTE_FACTOR_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_DIAMANTE_FACTOR_ID ON CFG_DIAMANTE_FACTOR(ID);
CREATE INDEX IDX_CFG_DIAMANTE_FACTOR_FECHA_CARGA ON CFG_DIAMANTE_FACTOR(FECHA_CARGA);

DROP TABLE IF EXISTS CFG_ALHAJA_LISTADO_FACTOR;
CREATE TABLE CFG_ALHAJA_LISTADO_FACTOR
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);
ALTER TABLE CFG_ALHAJA_LISTADO_FACTOR ADD CONSTRAINT PK_CFG_ALHAJA_LISTADO_FACTOR_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_ALHAJA_LISTADO_FACTOR_ID ON CFG_ALHAJA_LISTADO_FACTOR(ID);

DROP TABLE IF EXISTS CFG_FACTOR_ALHAJA;
CREATE TABLE CFG_FACTOR_ALHAJA
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    METAL VARCHAR(20) NOT NULL,
    CALIDAD VARCHAR(20),
    RANGO VARCHAR(20) NOT NULL,
    FACTOR DECIMAL(8, 2) NOT NULL,
    DESPLAZAMIENTO DECIMAL(8, 2) NOT NULL,
    LIMITE_INFERIOR DECIMAL(8, 2) NOT NULL,
    LIMITE_SUPERIOR DECIMAL(8, 2) NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    LISTADO BIGINT
);
ALTER TABLE CFG_FACTOR_ALHAJA ADD CONSTRAINT PK_CFG_FACTOR_ALHAJA_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_FACTOR_ALHAJA_ID ON CFG_FACTOR_ALHAJA(ID);
ALTER TABLE CFG_FACTOR_ALHAJA ADD CONSTRAINT FK_CFG_FACTOR_ALHAJA_CFG_ALHAJA_LISTADO_FACTOR
FOREIGN KEY(LISTADO) REFERENCES CFG_ALHAJA_LISTADO_FACTOR(ID);


DROP TABLE IF EXISTS HIST_CFG_ALHAJA_LISTADO_FACTOR;
CREATE TABLE HIST_CFG_ALHAJA_LISTADO_FACTOR
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);

DROP TABLE IF EXISTS HIST_CFG_FACTOR_ALHAJA;
CREATE TABLE HIST_CFG_FACTOR_ALHAJA
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    METAL VARCHAR(20) NOT NULL,
    CALIDAD VARCHAR(20),
    RANGO VARCHAR(20) NOT NULL,
    FACTOR DECIMAL(8, 2) NOT NULL,
    DESPLAZAMIENTO DECIMAL(8, 2) NOT NULL,
    LIMITE_INFERIOR DECIMAL(8, 2) NOT NULL,
    LIMITE_SUPERIOR DECIMAL(8, 2) NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    LISTADO BIGINT
);
ALTER TABLE HIST_CFG_FACTOR_ALHAJA ADD CONSTRAINT PK_HIST_CFG_FACTOR_ALHAJA_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_FACTOR_ALHAJA_ID ON HIST_CFG_FACTOR_ALHAJA(ID);
ALTER TABLE HIST_CFG_FACTOR_ALHAJA ADD CONSTRAINT FK_HIST_CFG_FACTOR_ALHAJA_HIST_CFG_ALHAJA_LISTADO_FACTOR
FOREIGN KEY(LISTADO) REFERENCES HIST_CFG_ALHAJA_LISTADO_FACTOR(ID);

DROP TABLE IF EXISTS CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO;
CREATE TABLE CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);
ALTER TABLE CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO ADD CONSTRAINT PK_CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO_ID ON CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO(ID);

DROP TABLE IF EXISTS CFG_DIAMANTE_VALOR_CERTIFICADO;
CREATE TABLE CFG_DIAMANTE_VALOR_CERTIFICADO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CERTIFICADO VARCHAR(20) NOT NULL,
    FACTOR DECIMAL(10, 3) NOT NULL,
    LISTADO BIGINT
);
ALTER TABLE CFG_DIAMANTE_VALOR_CERTIFICADO ADD CONSTRAINT PK_CFG_DIAMANTE_VALOR_CERTIFICADO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_DIAMANTE_VALOR_CERTIFICADO_ID ON CFG_DIAMANTE_VALOR_CERTIFICADO(ID);
ALTER TABLE CFG_DIAMANTE_VALOR_CERTIFICADO ADD CONSTRAINT FK_CFG_DIAMANTE_VALOR_CERTIFICADO_LISTADO
FOREIGN KEY(LISTADO) REFERENCES CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO(ID);

DROP TABLE IF EXISTS HIST_CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO;
CREATE TABLE HIST_CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);

DROP TABLE IF EXISTS HIST_CFG_DIAMANTE_VALOR_CERTIFICADO;
CREATE TABLE HIST_CFG_DIAMANTE_VALOR_CERTIFICADO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CERTIFICADO VARCHAR(20) NOT NULL,
    FACTOR DECIMAL(10, 3) NOT NULL,
    LISTADO BIGINT
);
ALTER TABLE HIST_CFG_DIAMANTE_VALOR_CERTIFICADO ADD CONSTRAINT PK_HIST_CFG_DIAMANTE_VALOR_CERTIFICADO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_DIAMANTE_VALOR_CERTIFICADO_ID ON HIST_CFG_DIAMANTE_VALOR_CERTIFICADO(ID);
ALTER TABLE HIST_CFG_DIAMANTE_VALOR_CERTIFICADO ADD CONSTRAINT FK_HIST_CFG_DIAMANTE_VALOR_CERTIFICADO
FOREIGN KEY(LISTADO) REFERENCES HIST_CFG_DIAMANTE_LISTADO_VALOR_CERTIFICADO(ID);



------------------------------------------------------------------------------------------------------------------------
-- INICIA - TABLAS: VALOR COMERCIAL 'DIAMANTE'
------------------------------------------------------------------------------------------------------------------------

--
-- HISTÓRICOS
--

DROP TABLE IF EXISTS HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL;
CREATE TABLE HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    FECHA_CARGA TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);

ALTER TABLE HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL ADD CONSTRAINT PK_HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL_ID ON HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL(ID);

DROP TABLE IF EXISTS HIST_CFG_DIAMANTE_VALOR_COMERCIAL;
CREATE TABLE HIST_CFG_DIAMANTE_VALOR_COMERCIAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CORTE VARCHAR(20) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    CLARIDAD VARCHAR(20) NOT NULL,
    TAMANIO_INFERIOR DECIMAL(6, 2) NOT NULL,
    TAMANIO_SUPERIOR DECIMAL(6, 2) NOT NULL,
    PRECIO DECIMAL(10, 4) NOT NULL,
    LISTADO BIGINT,
    TIPO_CAMBIO DECIMAL(12,4) NOT NULL,
    MONTOVBD DECIMAL(12, 4) NOT NULL,
    MONTOFCASTIGOXRANGO DECIMAL(12, 4) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_HIST_CFG_DIAMANTE_VALOR_COMERCIAL_ID ON HIST_CFG_DIAMANTE_VALOR_COMERCIAL(ID);
ALTER TABLE HIST_CFG_DIAMANTE_VALOR_COMERCIAL ADD CONSTRAINT FK_HIST_CFG_DIAMANTE_VALOR_COMERCIAL
FOREIGN KEY(LISTADO) REFERENCES HIST_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL(ID) ON DELETE CASCADE;

--
-- VIGENTES
--

DROP TABLE IF EXISTS CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL;
CREATE TABLE CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    FECHA_CARGA TIMESTAMP NOT NULL,
    FECHA_LISTADO DATE NOT NULL
);

ALTER TABLE CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL ADD CONSTRAINT PK_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL_ID ON CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL(ID);

DROP TABLE IF EXISTS CFG_DIAMANTE_VALOR_COMERCIAL;
CREATE TABLE CFG_DIAMANTE_VALOR_COMERCIAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CORTE VARCHAR(20) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    CLARIDAD VARCHAR(20) NOT NULL,
    TAMANIO_INFERIOR DECIMAL(6, 2) NOT NULL,
    TAMANIO_SUPERIOR DECIMAL(6, 2) NOT NULL,
    PRECIO DECIMAL(10, 4) NOT NULL,
    LISTADO BIGINT,
    TIPO_CAMBIO DECIMAL(12,4) NOT NULL,
    MONTOVBD DECIMAL(12, 4) NOT NULL,
    MONTOFCASTIGOXRANGO DECIMAL(12, 4) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_CFG_DIAMANTE_VALOR_COMERCIAL_ID ON CFG_DIAMANTE_VALOR_COMERCIAL(ID);
ALTER TABLE CFG_DIAMANTE_VALOR_COMERCIAL ADD CONSTRAINT FK_CFG_DIAMANTE_VALOR_COMERCIAL
FOREIGN KEY(LISTADO) REFERENCES CFG_DIAMANTE_LISTADO_VALOR_COMERCIAL(ID) ON DELETE CASCADE;

------------------------------------------------------------------------------------------------------------------------
-- TERMINA - TABLAS: VALOR COMERCIAL 'DIAMANTE'
------------------------------------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------------------------------------
-- INICIA - TABLAS: VALOR COMERCIAL 'ORO'
------------------------------------------------------------------------------------------------------------------------

--
-- HISTÓRICOS
--

DROP TABLE IF EXISTS HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO;
CREATE TABLE HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL
);

ALTER TABLE HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO ADD CONSTRAINT PK_HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO_ID ON HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO(ID);

DROP TABLE IF EXISTS HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO;
CREATE TABLE HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    CALIDAD VARCHAR(20) NOT NULL,
    PRECIO DECIMAL(10, 3) NOT NULL,
    LISTADO BIGINT
);

ALTER TABLE HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO ADD CONSTRAINT PK_HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO_ID ON HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO(ID);
ALTER TABLE HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO ADD CONSTRAINT FK_HIST_CFG_ALHAJA_VALOR_COMERCIAL_ORO
FOREIGN KEY(LISTADO) REFERENCES HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO(ID);

--
-- VIGENTES
--

DROP TABLE IF EXISTS CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO;
CREATE TABLE CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL
);

ALTER TABLE CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO ADD CONSTRAINT PK_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO_ID ON CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO(ID);

DROP TABLE IF EXISTS CFG_ALHAJA_VALOR_COMERCIAL_ORO;
CREATE TABLE CFG_ALHAJA_VALOR_COMERCIAL_ORO
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    CALIDAD VARCHAR(20) NOT NULL,
    PRECIO DECIMAL(10, 3) NOT NULL,
    LISTADO BIGINT
);

ALTER TABLE CFG_ALHAJA_VALOR_COMERCIAL_ORO ADD CONSTRAINT PK_CFG_ALHAJA_VALOR_COMERCIAL_ORO_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_ALHAJA_VALOR_COMERCIAL_ORO_ID ON CFG_ALHAJA_VALOR_COMERCIAL_ORO(ID);
ALTER TABLE CFG_ALHAJA_VALOR_COMERCIAL_ORO ADD CONSTRAINT FK_CFG_ALHAJA_VALOR_COMERCIAL_ORO
FOREIGN KEY(LISTADO) REFERENCES CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_ORO(ID);

------------------------------------------------------------------------------------------------------------------------
-- TERMINA - TABLAS: VALOR COMERCIAL 'ORO'
------------------------------------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------------------------------------
-- INICIA - TABLAS: VALOR COMERCIAL 'METAL'
------------------------------------------------------------------------------------------------------------------------

--
-- HISTÓRICOS
--

DROP TABLE IF EXISTS HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL;
CREATE TABLE HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL
);

ALTER TABLE HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL ADD CONSTRAINT PK_HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL_ID ON HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL(ID);

DROP TABLE IF EXISTS HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL;
CREATE TABLE HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    METAL VARCHAR(20) NOT NULL,
    CALIDAD VARCHAR(20),
    PRECIO DECIMAL(10, 3) NOT NULL,
    LISTADO BIGINT
);

ALTER TABLE HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL ADD CONSTRAINT PK_HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL_ID PRIMARY KEY(ID);
CREATE INDEX IDX_HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL_ID ON HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL(ID);
ALTER TABLE HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL ADD CONSTRAINT FK_HIST_CFG_ALHAJA_VALOR_COMERCIAL_METAL
FOREIGN KEY(LISTADO) REFERENCES HIST_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL(ID);

--
-- VIGENTES
--

DROP TABLE IF EXISTS CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL;
CREATE TABLE CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP NOT NULL
);

ALTER TABLE CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL ADD CONSTRAINT PK_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL_ID ON CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL(ID);

DROP TABLE IF EXISTS CFG_ALHAJA_VALOR_COMERCIAL_METAL;
CREATE TABLE CFG_ALHAJA_VALOR_COMERCIAL_METAL
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    METAL VARCHAR(20) NOT NULL,
    CALIDAD VARCHAR(20),
    PRECIO DECIMAL(10, 3) NOT NULL,
    LISTADO BIGINT
);

ALTER TABLE CFG_ALHAJA_VALOR_COMERCIAL_METAL ADD CONSTRAINT PK_CFG_ALHAJA_VALOR_COMERCIAL_METAL_ID PRIMARY KEY(ID);
CREATE INDEX IDX_CFG_ALHAJA_VALOR_COMERCIAL_METAL_ID ON CFG_ALHAJA_VALOR_COMERCIAL_METAL(ID);
ALTER TABLE CFG_ALHAJA_VALOR_COMERCIAL_METAL ADD CONSTRAINT FK_CFG_ALHAJA_VALOR_COMERCIAL_METAL
FOREIGN KEY(LISTADO) REFERENCES CFG_ALHAJA_LISTADO_VALOR_COMERCIAL_METAL(ID);

------------------------------------------------------------------------------------------------------------------------
-- TERMINA - TABLAS: VALOR COMERCIAL 'METAL'
------------------------------------------------------------------------------------------------------------------------

-- Inicio Nuevas tablas para Siva Diamantes F2

--
-- Table structure for table `cfg_diamante_factores_x_rango_de_color`
--

DROP TABLE IF EXISTS `cfg_diamante_factores_x_rango_de_color`;
CREATE TABLE `cfg_diamante_factores_x_rango_de_color` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FECHA` date NOT NULL,
  `COLOR_DESDE` varchar(20) NOT NULL,
  `COLOR_HASTA` varchar(20) NOT NULL,
  `RANGO_COLOR_BASE` varchar(20) NOT NULL,
  `FACTOR` decimal(10,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;



--
-- Table structure for table `cfg_diamante_porcentaje_castigo_x_rango_de_pesos`
--

DROP TABLE IF EXISTS `cfg_diamante_porcentaje_castigo_x_rango_de_pesos`;
CREATE TABLE `cfg_diamante_porcentaje_castigo_x_rango_de_pesos` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FECHA` date NOT NULL,
  `QUILATES_DESDE` decimal(10,2) NOT NULL,
  `QUILATES_HASTA` decimal(10,2) NOT NULL,
  `FACTOR` decimal(10,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;



--
-- Table structure for table `cfg_diamante_porcentaje_castigo_x_tipo_corte`
--

DROP TABLE IF EXISTS `cfg_diamante_porcentaje_castigo_x_tipo_corte`;
CREATE TABLE `cfg_diamante_porcentaje_castigo_x_tipo_corte` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FECHA` date NOT NULL,
  `CORTE` varchar(20) NOT NULL,
  `FACTOR` decimal(10,4) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--
-- Table structure for table `cfg_diamante_rango_pesos`
--

DROP TABLE IF EXISTS `cfg_diamante_rango_pesos`;
CREATE TABLE `cfg_diamante_rango_pesos` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FECHA` date NOT NULL,
  `QUILATES_DESDE` decimal(10,4) NOT NULL,
  `QUILATES_HASTA` decimal(10,4) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--
-- Table structure for table `cfg_diamante_parametros_quilates`
--

DROP TABLE IF EXISTS `cfg_diamante_parametros_quilates`;
CREATE TABLE `cfg_diamante_parametros_quilates` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FECHA` date NOT NULL,
  `QUILATES_DESDE` decimal(10,2) NOT NULL,
  `QUILATES_HASTA` decimal(10,2) NOT NULL,
  `QUILATES_BASE_DESDE` decimal(10,2) NOT NULL,
  `QUILATES_BASE_HASTA` decimal(10,2) NOT NULL,
  `PORCENTAJE` decimal(10,3) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

--
-- Table structure for table `cfg_diamante_factor_depreciacion`
--

DROP TABLE IF EXISTS `cfg_diamante_factor_depreciacion`;
CREATE TABLE `cfg_diamante_factor_depreciacion` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FACTOR` decimal(10,1) NOT NULL,
  `FECHA` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Fin Nuevas tablas para Siva Diamantes F2
